# Generated by Django 3.1.7 on 2021-03-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_userprofile_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data',
        ),
    ]
