# Generated by Django 3.1.7 on 2021-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_remove_userprofile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data',
            field=models.DateField(default='1980-01-01'),
        ),
    ]
